### PR TITLE
Change on the branch

### PR DESCRIPTION
**Pull request by elasticdog**
I'm going to have a change pushed to master upstream and see how things work with the protected branch, if this PR will be considered up-to-date or not when homu is handling things.

### CODE REVIEW

**Comment by ghost** [comment]
:umbrella: The latest upstream changes (presumably b0cace9) made this pull request unmergeable. Please resolve the merge conflicts.

**Comment by elasticdog** [comment]
@asbru r+

**Comment by ghost** [comment]
:pushpin: Commit 1821872 has been approved by `elasticdog`

**Comment by ghost** [comment]
:hourglass: Testing commit 1821872 with merge da42ff9...

**Comment by ghost** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/elasticdog/gateway/builds/143418102)
Approved by: elasticdog
Pushing da42ff960deb7436ecbf06f679087dbed0205d60 to master...

**Pull request merged**
