### PR TITLE
first change, second to be approved

### PR DESCRIPTION
**Pull request by elasticdog**

### CODE REVIEW

**Comment by elasticdog** [comment]
@asbru r+

**Comment by ghost** [comment]
:pushpin: Commit 247f043 has been approved by `elasticdog`

**Comment by ghost** [comment]
:hourglass: Testing commit 247f043 with merge 14ab30f...

**Comment by ghost** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/elasticdog/gateway/builds/143427671)

**Comment by elasticdog** [comment]
@asbru retry

**Comment by ghost** [comment]
:hourglass: Testing commit 247f043 with merge 3210768...

**Comment by ghost** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/elasticdog/gateway/builds/143435222)

**Comment by elasticdog** [comment]
@asbru retry

**Comment by ghost** [comment]
:hourglass: Testing commit 247f043 with merge b386d44...

**Comment by ghost** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/elasticdog/gateway/builds/143436259)
Approved by: elasticdog
Pushing b386d44cd6005ac853374ee37b98764e75627cbd to master...

**Pull request merged**
