### PR TITLE
second change, first to be approved

### PR DESCRIPTION
**Pull request by elasticdog**

### CODE REVIEW

**Comment by elasticdog** [comment]
@asbru r+

**Comment by ghost** [comment]
:pushpin: Commit bfa8d9c has been approved by `elasticdog`

**Comment by ghost** [comment]
:hourglass: Testing commit bfa8d9c with merge 3480e9b...

**Comment by ghost** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/elasticdog/gateway/builds/143427243)
Approved by: elasticdog
Pushing 3480e9b9490dbb01d179c81ec0c153cd7719d732 to master...

**Pull request merged**
