### PR TITLE
Testing the homu interface

### PR DESCRIPTION
**Pull request by elasticdog**

### CODE REVIEW

**Comment by elasticdog** [comment]
@asbru try

**Comment by elasticdog** [comment]
@asbru try

**Comment by ghost** [comment]
:hourglass: Trying commit c1f99a7 with merge 19dac3d...

**Comment by elasticdog** [comment]
@asbru clean try

**Comment by elasticdog** [comment]
@asbru clean

**Comment by elasticdog** [comment]
@asbru try

**Comment by elasticdog** [comment]
@asbru force

**Comment by elasticdog** [comment]
@asbru retry

**Comment by ghost** [comment]
:hourglass: Trying commit c1f99a7 with merge 7be4a9d...

**Comment by ghost** [comment]
:broken_heart: Test failed - [travis](https://travis-ci.org/elasticdog/gateway/builds/143241228)

**Comment by elasticdog** [comment]
@asbru clean

**Comment by elasticdog** [comment]
@asbru retry

**Comment by ghost** [comment]
:hourglass: Trying commit c1f99a7 with merge 25fb9e0...

**Comment by elasticdog** [comment]
@asbru force

**Comment by ghost** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/elasticdog/gateway/builds/143241924)
State: approved= try=True

**Comment by elasticdog** [comment]
@asbru r+

**Comment by ghost** [comment]
:pushpin: Commit c1f99a7 has been approved by `elasticdog`

**Comment by elasticdog** [comment]
@asbru clean

**Comment by elasticdog** [comment]
@asbru retry

**Comment by ghost** [comment]
:hourglass: Testing commit c1f99a7 with merge b8bad8d...

**Comment by ghost** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/elasticdog/gateway/builds/143243145)
Approved by: elasticdog
Pushing b8bad8d31510d1470f89d168ff5a1eb7fbb18799 to master...

**Comment by elasticdog** [comment]
this is an edited comment

**Comment by elasticdog** [comment]
This is a multi-line comment.

@gulbot r+

...and some more info

**Pull request merged**
