### PR TITLE
will push after this is approved

### PR DESCRIPTION
**Pull request by elasticdog**

### CODE REVIEW

**Comment by elasticdog** [comment]
@asbru r+

**Comment by ghost** [comment]
:pushpin: Commit 065b249 has been approved by `elasticdog`

**Comment by ghost** [comment]
:hourglass: Testing commit 065b249 with merge 0de49a7...

**Comment by elasticdog** [comment]
@asbru r+

**Comment by ghost** [comment]
:pushpin: Commit 607a717 has been approved by `elasticdog`

**Comment by ghost** [comment]
:hourglass: Testing commit 607a717 with merge 5ff3f83...

**Comment by ghost** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/elasticdog/gateway/builds/143440832)
Approved by: elasticdog
Pushing 5ff3f833555d3b49f83f62dae3eb03195f080925 to master...

**Pull request merged**
