### PR TITLE
Checking out linear

### PR DESCRIPTION
**Pull request by elasticdog**

### CODE REVIEW

**Comment by elasticdog** [comment]
@asbru r+

**Comment by ghost** [comment]
:pushpin: Commit 8e3fc80 has been approved by `elasticdog`

**Comment by ghost** [comment]
:hourglass: Testing commit 8e3fc80 with merge 8150e9e...

**Comment by ghost** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/elasticdog/gateway/builds/143424900)
Approved by: elasticdog
Pushing 8150e9eaee0393411a20c6f56591b3863f90f397 to master...

**Pull request merged**
