### PR TITLE
Go back to the beginning

### PR DESCRIPTION
**Pull request by elasticdog**
Let's test with a protected master branch to see the workflow.

### CODE REVIEW

**Comment by elasticdog** [comment]
@asbru try

**Comment by ghost** [comment]
:hourglass: Trying commit 7c9e5d9 with merge 4d1d7f3...

**Comment by ghost** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/elasticdog/gateway/builds/143408899)
State: approved= try=True

**Comment by elasticdog** [comment]
@asbru r+ 7c9e5d9

**Comment by elasticdog** [comment]
@asbru retry

**Comment by ghost** [comment]
:lock: Merge conflict

**Comment by elasticdog** [comment]
I rebased to fix the merge conflict...let's see how this gets handled. Also, can I do commands within a message? @asbru r+ what about other things after the commands?

**Comment by ghost** [comment]
:pushpin: Commit 49e4f8c has been approved by `elasticdog`

**Comment by ghost** [comment]
:hourglass: Testing commit 49e4f8c with merge 6fcd7aa...

**Comment by elasticdog** [comment]
@asbru r-

**Comment by ghost** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/elasticdog/gateway/builds/143413453)
State: approved= try=False

**Comment by elasticdog** [comment]
@asbru clean

I'm still not sure what clean does.

**Comment by elasticdog** [comment]
@asbru r+

**Comment by ghost** [comment]
:pushpin: Commit 49e4f8c has been approved by `elasticdog`

**Comment by elasticdog** [comment]
@asbru force

**Comment by elasticdog** [comment]
@asbru retry

**Comment by ghost** [comment]
:hourglass: Testing commit 49e4f8c with merge d4373c6...

**Comment by elasticdog** [comment]
@asbru force

**Comment by ghost** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/elasticdog/gateway/builds/143415215)
Approved by: elasticdog
Pushing d4373c6290453ec0f205864acf64ae54dcc4d500 to master...

**Pull request merged**
